BEGIN;
ALTER TABLE public.empresas DROP CONSTRAINT IF EXISTS empresas_status_check;
ALTER TABLE public.empresas ADD CONSTRAINT empresas_status_check CHECK (status IN (
 'CADASTRO_CONCLUIDO','ORCAMENTO_SOLICITADO','LISTA_FUNCIONARIOS_ENVIADA','PENDENTE_PAGAMENTO','ATIVO','INATIVO'
));
COMMIT;
